name: Build and Test

on:
  - push
  - pull_request

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 5.4

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: true
          allow-prerelease-opam: true

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: opam install . --deps-only --with-test

      - name: build project
        run: opam exec -- dune build

      - name: run test
        run: opam exec -- dune runtest
